import type { OptionGroup, PaletteColour, SuitConfig, SuitFabric } from "./types";

/**
 * The custom-suit catalogue — cloths, palettes, every configurable option
 * and its KES surcharge. This single file is the source of truth for both
 * the configurator UI and server-side order pricing, so the price a customer
 * sees is by construction the price they are charged.
 *
 * Extending it:
 *  - New cloth: append to SUIT_FABRICS (unique id). Retire one with
 *    `available: false` — never delete, old orders still reference it.
 *  - New option value: append to that group's `values`. Give it a `glyph`
 *    if components/suit/OptionGlyph.tsx should draw it; otherwise the tile
 *    shows its label.
 *  - New option group: append to OPTION_GROUPS, then add any dependency
 *    rule to lib/suit/rules.ts and (optionally) its drawing to
 *    components/suit/SuitPreview.tsx.
 *  - Bump CATALOGUE_VERSION whenever a price changes — every order stores
 *    the version it was priced against.
 */
export const CATALOGUE_VERSION = "2026-09-24.1";

/** Standard make: fitting to collection. Priority service shortens it. */
export const LEAD_TIME_DAYS = { standard: 21, priority: 12 } as const;

/** Share of the two-piece cloth price attributed to each piece. */
export const PIECE_SHARE = { jacket: 0.62, trousers: 0.38, waistcoat: 0.26 } as const;

export const MAX_SUITS_PER_LINE = 5;
export const DEPOSIT_RATE = 0.5;

export const COLLECTION_LABELS: Record<SuitFabric["collection"], string> = {
  house: "House",
  classic: "Classic",
  premium: "Premium",
  luxury: "Luxury",
  seasonal: "Seasonal",
};

export const SUIT_FABRICS: SuitFabric[] = [
  // ---- House (everyday, easy-care, comfort stretch) ----
  {
    id: "house-navy-stretch",
    name: "House Navy Stretch",
    collection: "house",
    price: 32000,
    composition: "65% wool, 32% polyester, 3% elastane",
    origin: "Turkey",
    weightGsm: 260,
    pattern: "twill",
    hex: "#232f4b",
    colourName: "Navy",
    colourFamily: "navy",
    season: "year-round",
    occasions: ["business", "wedding", "smart-casual"],
    features: ["Comfort stretch", "Easy iron", "Crease resistant"],
    stretch: true,
    description: "The house workhorse — a soft navy twill with a little give, built for Nairobi office days and long wedding receptions.",
    badge: "Best-seller",
    available: true,
  },
  {
    id: "house-charcoal-stretch",
    name: "House Charcoal Stretch",
    collection: "house",
    price: 32000,
    composition: "65% wool, 32% polyester, 3% elastane",
    origin: "Turkey",
    weightGsm: 260,
    pattern: "twill",
    hex: "#38393c",
    colourName: "Charcoal",
    colourFamily: "charcoal",
    season: "year-round",
    occasions: ["business", "celebration"],
    features: ["Comfort stretch", "Easy iron"],
    stretch: true,
    description: "Charcoal twill that shrugs off a matatu commute — the sensible first suit.",
    available: true,
  },
  {
    id: "house-grey-melange",
    name: "House Grey Melange",
    collection: "house",
    price: 32000,
    composition: "60% wool, 40% polyester",
    origin: "Turkey",
    weightGsm: 250,
    pattern: "melange",
    hex: "#7c7e82",
    accentHex: "#9a9ca0",
    colourName: "Mid grey",
    colourFamily: "grey",
    season: "year-round",
    occasions: ["business", "smart-casual"],
    features: ["Breathable", "Easy iron"],
    stretch: false,
    description: "A heathered mid-grey that pairs with everything from white poplin to a black roll-neck.",
    available: true,
  },
  {
    id: "house-black",
    name: "House Black",
    collection: "house",
    price: 32000,
    composition: "65% wool, 35% polyester",
    origin: "Turkey",
    weightGsm: 260,
    pattern: "solid",
    hex: "#151517",
    colourName: "Black",
    colourFamily: "black",
    season: "year-round",
    occasions: ["celebration", "wedding"],
    features: ["Deep black", "Easy iron"],
    stretch: false,
    description: "True black for evenings, ceremonies and the groomsmen line-up.",
    available: true,
  },

  // ---- Classic (worsted wools) ----
  {
    id: "classic-navy-s110",
    name: "Navy Super 110s",
    collection: "classic",
    price: 42000,
    composition: "100% wool",
    origin: "Italy",
    weightGsm: 250,
    superNumber: 110,
    pattern: "twill",
    hex: "#1d2945",
    colourName: "Navy",
    colourFamily: "navy",
    season: "year-round",
    occasions: ["business", "wedding"],
    features: ["Pure wool", "Natural stretch"],
    stretch: false,
    description: "Pure wool worsted in a deep navy — the definitive business suit.",
    badge: "House pick",
    available: true,
  },
  {
    id: "classic-grey-s110",
    name: "Mid Grey Super 110s",
    collection: "classic",
    price: 42000,
    composition: "100% wool",
    origin: "Italy",
    weightGsm: 250,
    superNumber: 110,
    pattern: "twill",
    hex: "#6e7176",
    colourName: "Mid grey",
    colourFamily: "grey",
    season: "year-round",
    occasions: ["business"],
    features: ["Pure wool"],
    stretch: false,
    description: "Clean mid-grey worsted; lifts in daylight, sober at night.",
    available: true,
  },
  {
    id: "fab-mid-blue-twill",
    name: "Mid-Blue Twill",
    collection: "classic",
    price: 44000,
    composition: "100% wool",
    origin: "England",
    weightGsm: 260,
    pattern: "twill",
    hex: "#4a6190",
    colourName: "Mid blue",
    colourFamily: "blue",
    season: "year-round",
    occasions: ["wedding", "smart-casual", "business"],
    features: ["Pure wool"],
    stretch: false,
    description: "A brighter English twill — confident at a daytime wedding.",
    image: "/photos/fabrics/mid-blue-twill.jpg",
    available: true,
  },
  {
    id: "classic-olive-twill",
    name: "Olive Twill Super 100s",
    collection: "classic",
    price: 44000,
    composition: "100% wool",
    origin: "Italy",
    weightGsm: 260,
    superNumber: 100,
    pattern: "twill",
    hex: "#4d5a3b",
    colourName: "Olive",
    colourFamily: "green",
    season: "year-round",
    occasions: ["wedding", "smart-casual"],
    features: ["Pure wool"],
    stretch: false,
    description: "Olive worsted with a quiet twill line — the groom who doesn't want navy.",
    badge: "New",
    available: true,
  },
  {
    id: "classic-navy-pinstripe",
    name: "Navy Pinstripe",
    collection: "classic",
    price: 46000,
    composition: "100% wool",
    origin: "Italy",
    weightGsm: 260,
    superNumber: 110,
    pattern: "pinstripe",
    hex: "#1f2a44",
    accentHex: "#b9bfcc",
    colourName: "Navy / white pin",
    colourFamily: "navy",
    season: "year-round",
    occasions: ["business"],
    features: ["Pure wool"],
    stretch: false,
    description: "A fine white pin on navy — boardroom classic.",
    available: true,
  },
  {
    id: "classic-charcoal-chalkstripe",
    name: "Charcoal Chalk Stripe",
    collection: "classic",
    price: 48000,
    composition: "100% wool",
    origin: "England",
    weightGsm: 290,
    pattern: "chalkstripe",
    hex: "#34363a",
    accentHex: "#8c8f94",
    colourName: "Charcoal / chalk",
    colourFamily: "charcoal",
    season: "year-round",
    occasions: ["business"],
    features: ["Pure wool", "Soft handle"],
    stretch: false,
    description: "A broad, soft chalk stripe on charcoal. Best double-breasted.",
    available: true,
  },
  {
    id: "classic-brown-herringbone",
    name: "Brown Herringbone",
    collection: "classic",
    price: 46000,
    composition: "100% wool",
    origin: "England",
    weightGsm: 300,
    pattern: "herringbone",
    hex: "#5a4636",
    accentHex: "#7a6250",
    colourName: "Tobacco brown",
    colourFamily: "brown",
    season: "winter",
    occasions: ["smart-casual", "business"],
    features: ["Pure wool"],
    stretch: false,
    description: "Tobacco herringbone for July mornings in Karen.",
    available: true,
  },
  {
    id: "fab-houndstooth",
    name: "Houndstooth",
    collection: "classic",
    price: 48000,
    composition: "100% wool",
    origin: "England",
    weightGsm: 300,
    pattern: "houndstooth",
    hex: "#2b2b2b",
    accentHex: "#cfcac0",
    colourName: "Black / ecru",
    colourFamily: "grey",
    season: "winter",
    occasions: ["smart-casual", "celebration"],
    features: ["Pure wool"],
    stretch: false,
    description: "Bold English houndstooth — a statement three-piece.",
    image: "/photos/fabrics/houndstooth.jpg",
    available: true,
  },

  // ---- Premium ----
  {
    id: "fab-charcoal-wool",
    name: "Charcoal Wool Super 120s",
    collection: "premium",
    price: 56000,
    composition: "100% wool",
    origin: "Italy",
    weightGsm: 280,
    superNumber: 120,
    pattern: "solid",
    hex: "#3b3d40",
    colourName: "Charcoal",
    colourFamily: "charcoal",
    season: "year-round",
    occasions: ["business", "celebration"],
    features: ["Pure wool", "Fine handle"],
    stretch: false,
    description: "Fine Italian charcoal with a dry, matte finish. Drapes beautifully.",
    image: "/photos/fabrics/charcoal-wool.jpg",
    available: true,
  },
  {
    id: "fab-navy-birdseye",
    name: "Navy Birdseye Super 130s",
    collection: "premium",
    price: 58000,
    composition: "100% wool",
    origin: "Italy",
    weightGsm: 250,
    superNumber: 130,
    pattern: "birdseye",
    hex: "#1e2a44",
    accentHex: "#3b4a6b",
    colourName: "Navy",
    colourFamily: "navy",
    season: "year-round",
    occasions: ["business", "wedding"],
    features: ["Pure wool", "Micro-pattern"],
    stretch: false,
    description: "A navy birdseye that reads solid across a room and rich up close.",
    image: "/photos/fabrics/navy-birdseye.jpg",
    available: true,
  },
  {
    id: "fab-ink-flannel",
    name: "Ink Flannel Super 100s",
    collection: "premium",
    price: 54000,
    composition: "100% wool",
    origin: "Italy",
    weightGsm: 320,
    superNumber: 100,
    pattern: "flannel",
    hex: "#1f2433",
    accentHex: "#2b3144",
    colourName: "Ink",
    colourFamily: "navy",
    season: "winter",
    occasions: ["business", "smart-casual"],
    features: ["Brushed", "Soft touch"],
    stretch: false,
    description: "Soft brushed flannel in ink — the cool-season suit.",
    image: "/photos/fabrics/ink-flannel.jpg",
    available: true,
  },
  {
    id: "premium-glencheck",
    name: "Grey Prince of Wales Check",
    collection: "premium",
    price: 58000,
    composition: "100% wool",
    origin: "Italy",
    weightGsm: 270,
    superNumber: 120,
    pattern: "glencheck",
    hex: "#8a8b8e",
    accentHex: "#5c6a86",
    colourName: "Grey / blue overcheck",
    colourFamily: "grey",
    season: "year-round",
    occasions: ["business", "wedding"],
    features: ["Pure wool"],
    stretch: false,
    description: "Glen check with a blue overcheck — a daytime-wedding favourite.",
    available: true,
  },
  {
    id: "premium-midnight-s130",
    name: "Midnight Super 130s",
    collection: "premium",
    price: 60000,
    composition: "100% wool",
    origin: "Italy",
    weightGsm: 260,
    superNumber: 130,
    pattern: "solid",
    hex: "#141a2b",
    colourName: "Midnight blue",
    colourFamily: "navy",
    season: "year-round",
    occasions: ["celebration", "wedding"],
    features: ["Pure wool", "Evening"],
    stretch: false,
    description: "Midnight blue reads blacker than black under lights — the dinner-suit cloth.",
    available: true,
  },
  {
    id: "premium-windowpane",
    name: "Blue-Grey Windowpane",
    collection: "premium",
    price: 56000,
    composition: "100% wool",
    origin: "England",
    weightGsm: 280,
    pattern: "windowpane",
    hex: "#59636f",
    accentHex: "#a5a9ae",
    colourName: "Slate / pane",
    colourFamily: "grey",
    season: "year-round",
    occasions: ["smart-casual", "business"],
    features: ["Pure wool"],
    stretch: false,
    description: "A slate cloth with a fine windowpane — pattern with restraint.",
    badge: "New",
    available: true,
  },

  // ---- Luxury ----
  {
    id: "luxury-navy-s150",
    name: "Navy Super 150s",
    collection: "luxury",
    price: 78000,
    composition: "100% extra-fine merino wool",
    origin: "Italy",
    weightGsm: 240,
    superNumber: 150,
    pattern: "solid",
    hex: "#1a2440",
    colourName: "Navy",
    colourFamily: "navy",
    season: "year-round",
    occasions: ["business", "wedding", "celebration"],
    features: ["Extra-fine merino", "Lustre", "Lightweight"],
    stretch: false,
    description: "Extra-fine Italian merino with a quiet lustre. For the day it matters.",
    available: true,
  },
  {
    id: "luxury-charcoal-s150",
    name: "Charcoal Super 150s",
    collection: "luxury",
    price: 78000,
    composition: "100% extra-fine merino wool",
    origin: "Italy",
    weightGsm: 240,
    superNumber: 150,
    pattern: "solid",
    hex: "#2f3134",
    colourName: "Charcoal",
    colourFamily: "charcoal",
    season: "year-round",
    occasions: ["business", "celebration"],
    features: ["Extra-fine merino", "Lustre"],
    stretch: false,
    description: "The same luxury merino in charcoal — soft, light and very quiet.",
    available: true,
  },

  // ---- Seasonal ----
  {
    id: "fab-oatmeal-linen",
    name: "Oatmeal Linen",
    collection: "seasonal",
    price: 42000,
    composition: "100% linen",
    origin: "Ireland",
    weightGsm: 220,
    pattern: "linen",
    hex: "#cbb89a",
    accentHex: "#b8a482",
    colourName: "Oatmeal",
    colourFamily: "beige",
    season: "summer",
    occasions: ["wedding", "smart-casual"],
    features: ["Breathable", "Natural slub"],
    stretch: false,
    description: "Irish linen for Mombasa and garden weddings. Creases with character.",
    image: "/photos/fabrics/oatmeal-linen.jpg",
    available: true,
  },
  {
    id: "fab-cream-linen-cotton",
    name: "Cream Linen-Cotton",
    collection: "seasonal",
    price: 40000,
    composition: "55% linen, 45% cotton",
    origin: "Portugal",
    weightGsm: 210,
    pattern: "linen",
    hex: "#e8dfcc",
    accentHex: "#d8ceb8",
    colourName: "Cream",
    colourFamily: "cream",
    season: "summer",
    occasions: ["wedding", "celebration"],
    features: ["Breathable", "Cool touch"],
    stretch: false,
    description: "Cream linen-cotton — creases less than pure linen, looks just as cool.",
    image: "/photos/fabrics/cream-linen-cotton.jpg",
    available: true,
  },
  {
    id: "seasonal-sage-linen",
    name: "Sage Linen Blend",
    collection: "seasonal",
    price: 42000,
    composition: "70% linen, 30% wool",
    origin: "Italy",
    weightGsm: 230,
    pattern: "linen",
    hex: "#8a977a",
    accentHex: "#7a876b",
    colourName: "Sage",
    colourFamily: "green",
    season: "summer",
    occasions: ["wedding", "smart-casual"],
    features: ["Breathable"],
    stretch: false,
    description: "Sage linen-wool — a soft green for outdoor ceremonies.",
    badge: "New",
    available: true,
  },
  {
    id: "seasonal-sky-cotton-linen",
    name: "Sky Cotton-Linen",
    collection: "seasonal",
    price: 40000,
    composition: "60% cotton, 40% linen",
    origin: "Portugal",
    weightGsm: 220,
    pattern: "linen",
    hex: "#9db3cc",
    accentHex: "#8ea5c0",
    colourName: "Sky blue",
    colourFamily: "blue",
    season: "summer",
    occasions: ["wedding", "smart-casual"],
    features: ["Breathable", "Cool touch"],
    stretch: false,
    description: "Pale sky cotton-linen for the coast.",
    available: true,
  },
  {
    id: "fab-olive-corduroy",
    name: "Olive Corduroy",
    collection: "seasonal",
    price: 46000,
    composition: "98% cotton, 2% elastane",
    origin: "Japan",
    weightGsm: 340,
    pattern: "corduroy",
    hex: "#5b5a3a",
    accentHex: "#4a4930",
    colourName: "Olive",
    colourFamily: "green",
    season: "winter",
    occasions: ["smart-casual"],
    features: ["Comfort stretch", "Soft touch"],
    stretch: true,
    description: "Fine-wale Japanese corduroy — a weekend suit that wears like a cardigan.",
    image: "/photos/fabrics/olive-corduroy.jpg",
    available: true,
  },
  {
    id: "seasonal-donegal-tweed",
    name: "Grey Donegal Tweed",
    collection: "seasonal",
    price: 52000,
    composition: "100% wool",
    origin: "Ireland",
    weightGsm: 380,
    pattern: "donegal",
    hex: "#6d6a63",
    accentHex: "#b0492f",
    colourName: "Grey with flecks",
    colourFamily: "grey",
    season: "winter",
    occasions: ["smart-casual"],
    features: ["Brushed", "Hard-wearing"],
    stretch: false,
    description: "Flecked Donegal tweed. Add elbow patches and you'll never take it off.",
    available: true,
  },
  {
    id: "seasonal-burgundy-velvet",
    name: "Burgundy Velvet",
    collection: "seasonal",
    price: 56000,
    composition: "100% cotton velvet",
    origin: "Italy",
    weightGsm: 330,
    pattern: "velvet",
    hex: "#5a1b26",
    accentHex: "#7a2a36",
    colourName: "Burgundy",
    colourFamily: "red",
    season: "winter",
    occasions: ["celebration"],
    features: ["Velvet pile", "Evening"],
    stretch: false,
    description: "Cotton velvet in deep burgundy — the dinner jacket for the end-of-year party.",
    available: true,
  },
];

export const LINING_COLOURS: PaletteColour[] = [
  { id: "oxblood", name: "Oxblood", hex: "#7a2f24" },
  { id: "burgundy", name: "Burgundy", hex: "#5c1a2a" },
  { id: "navy", name: "Navy", hex: "#1c2a4a" },
  { id: "royal", name: "Royal blue", hex: "#2446a0" },
  { id: "teal", name: "Teal", hex: "#1e6468" },
  { id: "bottle", name: "Bottle green", hex: "#1f4a33" },
  { id: "gold", name: "Old gold", hex: "#b08a3e" },
  { id: "champagne", name: "Champagne", hex: "#d9c9a3" },
  { id: "silver", name: "Silver grey", hex: "#a9acb1" },
  { id: "lilac", name: "Lilac", hex: "#8e7aa8" },
  { id: "black", name: "Black", hex: "#141416" },
  { id: "paisley-oxblood", name: "Oxblood paisley", hex: "#6e2a22", accentHex: "#d1a15a", kind: "paisley", price: 1000 },
  { id: "paisley-navy", name: "Navy paisley", hex: "#1b274a", accentHex: "#c9a35a", kind: "paisley", price: 1000 },
  { id: "kitenge-indigo", name: "Kitenge indigo", hex: "#23306b", accentHex: "#e0a93a", kind: "kitenge", price: 1500 },
  { id: "kitenge-amber", name: "Kitenge amber", hex: "#b4541e", accentHex: "#1d3a2a", kind: "kitenge", price: 1500 },
  { id: "geometric-gold", name: "Gold geometric", hex: "#1a1a1c", accentHex: "#b8913f", kind: "geometric", price: 1000 },
  { id: "bengal-stripe", name: "Bengal stripe", hex: "#e8e2d4", accentHex: "#7a2f24", kind: "stripe", price: 800 },
];

export const THREAD_COLOURS: PaletteColour[] = [
  { id: "cream", name: "Cream", hex: "#efe6d2" },
  { id: "white", name: "White", hex: "#f8f8f6" },
  { id: "black", name: "Black", hex: "#141416" },
  { id: "navy", name: "Navy", hex: "#1c2a4a" },
  { id: "oxblood", name: "Oxblood", hex: "#8a4432" },
  { id: "burgundy", name: "Burgundy", hex: "#6b1f30" },
  { id: "gold", name: "Gold", hex: "#c49a3c" },
  { id: "silver", name: "Silver", hex: "#b6b9be" },
  { id: "sky", name: "Sky", hex: "#8fb3d9" },
  { id: "emerald", name: "Emerald", hex: "#1f7a4f" },
  { id: "orange", name: "Burnt orange", hex: "#c8642a" },
  { id: "rose", name: "Rose", hex: "#c9788c" },
];

export const FELT_COLOURS: PaletteColour[] = [
  { id: "oxblood", name: "Oxblood", hex: "#7a2f24" },
  { id: "navy", name: "Navy", hex: "#1c2a4a" },
  { id: "bottle", name: "Bottle green", hex: "#1f4a33" },
  { id: "gold", name: "Mustard", hex: "#b8892f" },
  { id: "black", name: "Black", hex: "#141416" },
];

export const MONOGRAM_FONTS: { id: "script" | "serif" | "block"; label: string; css: string }[] = [
  { id: "script", label: "Script", css: "'Brush Script MT', 'Segoe Script', cursive" },
  { id: "serif", label: "Serif", css: "var(--font-display), Georgia, serif" },
  { id: "block", label: "Block", css: "var(--font-body), Arial, sans-serif" },
];

/** Buttons are an option group, but the preview also needs their colours. */
export const BUTTON_HEX: Record<string, string | null> = {
  matched: null,
  "horn-dark": "#3a2a20",
  "horn-light": "#a07a5a",
  corozo: "#8a6b4a",
  "mother-of-pearl": "#e9e4da",
  gold: "#c9a24a",
  silver: "#b8bcc2",
};

export const OPTION_GROUPS: OptionGroup[] = [
  // ---- Suit ----
  {
    id: "suit.pieces",
    section: "suit",
    label: "Pieces",
    display: "glyph",
    defaultValue: "two",
    values: [
      { id: "two", label: "Two-piece", description: "Jacket and trousers", glyph: "pieces-two" },
      { id: "three", label: "Three-piece", description: "Adds a matching waistcoat", glyph: "pieces-three" },
    ],
  },
  {
    id: "suit.fabricMode",
    section: "suit",
    label: "Mix & match fabrics",
    help: "Use one cloth throughout, or choose a different cloth for the trousers and waistcoat.",
    display: "glyph",
    defaultValue: "same",
    values: [
      { id: "same", label: "Same fabric", glyph: "fabric-same" },
      { id: "mixed", label: "Different fabrics", glyph: "fabric-mixed" },
    ],
  },
  {
    id: "suit.extraTrousers",
    section: "suit",
    label: "Extra trousers",
    help: "A second pair doubles the life of the suit — trousers wear out first.",
    display: "chip",
    defaultValue: "none",
    values: [
      { id: "none", label: "No extra pair" },
      { id: "one", label: "Add a second pair" },
    ],
  },

  // ---- Jacket ----
  {
    id: "jacket.fit",
    section: "jacket",
    label: "Jacket fit",
    display: "chip",
    defaultValue: "classic",
    values: [
      { id: "slim", label: "Slim", description: "Close through the chest and waist" },
      { id: "classic", label: "Classic", description: "Tailored with easy movement" },
      { id: "relaxed", label: "Relaxed", description: "Fuller cut, softer line" },
    ],
  },
  {
    id: "jacket.closure",
    section: "jacket",
    label: "Style",
    display: "glyph",
    defaultValue: "sb2",
    values: [
      { id: "sb1", label: "Single-breasted, 1 button", glyph: "closure-sb1" },
      { id: "sb2", label: "Single-breasted, 2 buttons", glyph: "closure-sb2" },
      { id: "sb3", label: "Single-breasted, 3 roll 2", glyph: "closure-sb3" },
      { id: "db4", label: "Double-breasted, 4 buttons", glyph: "closure-db4" },
      { id: "db6", label: "Double-breasted, 6 buttons", glyph: "closure-db6" },
      { id: "mandarin", label: "Mandarin collar", glyph: "closure-mandarin" },
    ],
  },
  {
    id: "jacket.lapel",
    section: "jacket",
    label: "Lapel style",
    display: "glyph",
    defaultValue: "notch",
    values: [
      { id: "notch", label: "Notch", glyph: "lapel-notch" },
      { id: "peak", label: "Peak", glyph: "lapel-peak" },
      { id: "shawl", label: "Shawl", glyph: "lapel-shawl" },
    ],
  },
  {
    id: "jacket.lapelWidth",
    section: "jacket",
    label: "Lapel width",
    display: "chip",
    defaultValue: "standard",
    values: [
      { id: "slim", label: "Slim · 6cm" },
      { id: "standard", label: "Standard · 8cm" },
      { id: "wide", label: "Wide · 10cm" },
    ],
  },
  {
    id: "jacket.lapelFacing",
    section: "jacket",
    label: "Lapel facing",
    help: "Satin facings turn a dark suit into evening wear.",
    display: "chip",
    advanced: true,
    defaultValue: "self",
    values: [
      { id: "self", label: "Self fabric" },
      { id: "satin", label: "Satin", price: 3500 },
    ],
  },
  {
    id: "jacket.shoulder",
    section: "jacket",
    label: "Shoulder",
    display: "chip",
    advanced: true,
    defaultValue: "natural",
    values: [
      { id: "natural", label: "Natural", description: "Light padding, soft line" },
      { id: "structured", label: "Structured", description: "Crisper, squarer line" },
      { id: "roped", label: "Roped", description: "Raised sleevehead", price: 1200 },
    ],
  },
  {
    id: "jacket.pockets",
    section: "jacket",
    label: "Pocket style",
    display: "glyph",
    defaultValue: "flap",
    values: [
      { id: "flap", label: "With flap", glyph: "pocket-flap" },
      { id: "jetted", label: "Double-welted", glyph: "pocket-jetted" },
      { id: "patch", label: "Patched", glyph: "pocket-patch" },
      { id: "none", label: "No pockets", glyph: "pocket-none" },
    ],
  },
  {
    id: "jacket.pocketSlant",
    section: "jacket",
    label: "Pocket angle",
    display: "chip",
    advanced: true,
    defaultValue: "straight",
    values: [
      { id: "straight", label: "Straight" },
      { id: "slanted", label: "Slanted (hacking)" },
    ],
  },
  {
    id: "jacket.ticketPocket",
    section: "jacket",
    label: "Ticket pocket",
    display: "chip",
    advanced: true,
    defaultValue: "none",
    values: [
      { id: "none", label: "None" },
      { id: "ticket", label: "Add ticket pocket", price: 900 },
    ],
  },
  {
    id: "jacket.breastPocket",
    section: "jacket",
    label: "Breast pocket",
    display: "chip",
    defaultValue: "welt",
    values: [
      { id: "welt", label: "Welt" },
      { id: "patch", label: "Patched" },
      { id: "none", label: "None" },
    ],
  },
  {
    id: "jacket.sleeveButtons",
    section: "jacket",
    label: "Sleeve buttons",
    display: "chip",
    defaultValue: "4",
    values: [
      { id: "2", label: "2" },
      { id: "3", label: "3" },
      { id: "4", label: "4" },
    ],
  },
  {
    id: "jacket.cuffs",
    section: "jacket",
    label: "Cuff buttonholes",
    display: "chip",
    advanced: true,
    defaultValue: "decorative",
    values: [
      { id: "decorative", label: "Decorative" },
      { id: "working", label: "Working cuffs", description: "Buttonholes that open", price: 1800 },
    ],
  },
  {
    id: "jacket.vents",
    section: "jacket",
    label: "Back style",
    display: "glyph",
    defaultValue: "side",
    values: [
      { id: "none", label: "Ventless", glyph: "vent-none" },
      { id: "centre", label: "Centre vent", glyph: "vent-centre" },
      { id: "side", label: "Side vents", glyph: "vent-side" },
    ],
  },

  // ---- Trousers ----
  {
    id: "trousers.fit",
    section: "trousers",
    label: "Trouser fit",
    display: "chip",
    defaultValue: "classic",
    values: [
      { id: "slim", label: "Slim", description: "Tapered leg" },
      { id: "classic", label: "Classic", description: "Straight, clean leg" },
      { id: "relaxed", label: "Relaxed", description: "Fuller thigh and leg" },
    ],
  },
  {
    id: "trousers.pleats",
    section: "trousers",
    label: "Pleats",
    display: "glyph",
    defaultValue: "none",
    values: [
      { id: "none", label: "Flat front", glyph: "pleat-none" },
      { id: "single", label: "Single pleat", glyph: "pleat-single" },
      { id: "double", label: "Double pleats", glyph: "pleat-double" },
    ],
  },
  {
    id: "trousers.fastening",
    section: "trousers",
    label: "Fastening",
    display: "chip",
    advanced: true,
    defaultValue: "centred",
    values: [
      { id: "centred", label: "Centred button" },
      { id: "extended", label: "Extended tab" },
      { id: "hidden", label: "Hidden hook" },
    ],
  },
  {
    id: "trousers.waist",
    section: "trousers",
    label: "Waist",
    display: "chip",
    defaultValue: "loops",
    values: [
      { id: "loops", label: "Belt loops" },
      { id: "adjusters", label: "Side adjusters", description: "Buckled tabs, no belt needed", price: 2000 },
      { id: "active", label: "Active waist", description: "Hidden elastic, gives one size", price: 2000 },
    ],
  },
  {
    id: "trousers.braces",
    section: "trousers",
    label: "Braces buttons",
    display: "chip",
    advanced: true,
    defaultValue: "none",
    values: [
      { id: "none", label: "None" },
      { id: "yes", label: "Add braces buttons", price: 900 },
    ],
  },
  {
    id: "trousers.sidePockets",
    section: "trousers",
    label: "Side pockets",
    display: "chip",
    advanced: true,
    defaultValue: "slanted",
    values: [
      { id: "slanted", label: "Slanted" },
      { id: "seam", label: "On-seam (vertical)" },
    ],
  },
  {
    id: "trousers.backPockets",
    section: "trousers",
    label: "Back pockets",
    display: "chip",
    advanced: true,
    defaultValue: "jetted2",
    values: [
      { id: "none", label: "None" },
      { id: "jetted1", label: "1 jetted, buttoned" },
      { id: "jetted2", label: "2 jetted, buttoned" },
      { id: "flap2", label: "2 with flaps" },
    ],
  },
  {
    id: "trousers.hem",
    section: "trousers",
    label: "Trouser hem",
    display: "chip",
    defaultValue: "plain",
    values: [
      { id: "plain", label: "Plain hem" },
      { id: "turnups", label: "Turn-ups (cuffs)" },
    ],
  },
  {
    id: "trousers.break",
    section: "trousers",
    label: "Break",
    help: "How much the trouser rests on the shoe.",
    display: "chip",
    advanced: true,
    defaultValue: "half",
    values: [
      { id: "none", label: "No break" },
      { id: "half", label: "Half break" },
      { id: "full", label: "Full break" },
    ],
  },

  // ---- Waistcoat ----
  {
    id: "waistcoat.style",
    section: "waistcoat",
    label: "Waistcoat style",
    display: "glyph",
    defaultValue: "sb5",
    values: [
      { id: "sb5", label: "Single-breasted, 5 buttons", glyph: "vest-sb5" },
      { id: "sb6", label: "Single-breasted, 6 buttons", glyph: "vest-sb6" },
      { id: "db6", label: "Double-breasted, 6 buttons", glyph: "vest-db6" },
    ],
  },
  {
    id: "waistcoat.lapel",
    section: "waistcoat",
    label: "Waistcoat lapels",
    display: "chip",
    defaultValue: "none",
    values: [
      { id: "none", label: "No lapels" },
      { id: "notch", label: "Notch" },
      { id: "peak", label: "Peak" },
      { id: "shawl", label: "Shawl" },
    ],
  },
  {
    id: "waistcoat.edge",
    section: "waistcoat",
    label: "Bottom edge",
    display: "chip",
    defaultValue: "pointed",
    values: [
      { id: "pointed", label: "Pointed" },
      { id: "straight", label: "Straight" },
    ],
  },
  {
    id: "waistcoat.pockets",
    section: "waistcoat",
    label: "Waistcoat pockets",
    display: "chip",
    advanced: true,
    defaultValue: "welt",
    values: [
      { id: "welt", label: "Welt pockets" },
      { id: "jetted", label: "Double-welted" },
      { id: "none", label: "No pockets" },
    ],
  },
  {
    id: "waistcoat.back",
    section: "waistcoat",
    label: "Waistcoat back",
    display: "chip",
    advanced: true,
    defaultValue: "lining",
    values: [
      { id: "lining", label: "Lining with adjuster" },
      { id: "fabric", label: "Suit fabric back", price: 2500 },
    ],
  },

  // ---- Accents / finishing ----
  {
    id: "accents.liningStyle",
    section: "accents",
    label: "Lining construction",
    display: "chip",
    defaultValue: "full",
    values: [
      { id: "full", label: "Fully lined" },
      { id: "half", label: "Half-lined", description: "Cooler; finished seams", price: 1800 },
      { id: "unlined", label: "Unlined", description: "Coolest; every seam bound", price: 3500 },
    ],
  },
  {
    id: "accents.liningColour",
    section: "accents",
    label: "Lining colour",
    display: "chip",
    defaultValue: "house",
    values: [
      { id: "house", label: "Tone-matched (house)" },
      { id: "custom", label: "Choose a colour or print", price: 2000 },
    ],
  },
  {
    id: "accents.buttons",
    section: "accents",
    label: "Buttons",
    display: "swatch",
    defaultValue: "matched",
    values: [
      { id: "matched", label: "Tone-matched" },
      { id: "horn-dark", label: "Dark horn", price: 1800, hex: "#3a2a20" },
      { id: "horn-light", label: "Light horn", price: 1800, hex: "#a07a5a" },
      { id: "corozo", label: "Corozo nut", price: 1200, hex: "#8a6b4a" },
      { id: "mother-of-pearl", label: "Mother of pearl", price: 2500, hex: "#e9e4da" },
      { id: "gold", label: "Gold metal", price: 2500, hex: "#c9a24a" },
      { id: "silver", label: "Silver metal", price: 2500, hex: "#b8bcc2" },
    ],
  },
  {
    id: "accents.buttonholes",
    section: "accents",
    label: "Buttonhole thread",
    display: "chip",
    defaultValue: "matched",
    values: [
      { id: "matched", label: "Tone-matched" },
      { id: "lapel", label: "Contrast lapel only", price: 900 },
      { id: "cuffs", label: "Contrast cuffs only", price: 1200 },
      { id: "all", label: "Contrast throughout", price: 1800 },
    ],
  },
  {
    id: "accents.monogram",
    section: "accents",
    label: "Monogram",
    display: "chip",
    defaultValue: "none",
    values: [
      { id: "none", label: "No monogram" },
      { id: "yes", label: "Add initials", price: 1300 },
    ],
  },
  {
    id: "accents.pickStitch",
    section: "accents",
    label: "Pick stitching",
    help: "Hand-finished stitch along the lapel and pocket edges.",
    display: "chip",
    defaultValue: "none",
    values: [
      { id: "none", label: "None" },
      { id: "yes", label: "Add pick stitching", price: 1500 },
    ],
  },
  {
    id: "accents.underCollar",
    section: "accents",
    label: "Under-collar felt",
    display: "swatch",
    advanced: true,
    defaultValue: "matched",
    values: [
      { id: "matched", label: "Tone-matched" },
      ...FELT_COLOURS.map((c) => ({ id: c.id, label: c.name, hex: c.hex, price: 900 })),
    ],
  },
  {
    id: "accents.elbowPatches",
    section: "accents",
    label: "Elbow patches",
    display: "swatch",
    advanced: true,
    defaultValue: "none",
    values: [
      { id: "none", label: "None" },
      { id: "tan", label: "Tan suede", hex: "#a8754a", price: 2200 },
      { id: "brown", label: "Brown suede", hex: "#5e3e2a", price: 2200 },
      { id: "navy", label: "Navy suede", hex: "#23304c", price: 2200 },
      { id: "olive", label: "Olive suede", hex: "#555a38", price: 2200 },
    ],
  },
  {
    id: "accents.pocketSquare",
    section: "accents",
    label: "Pocket square",
    display: "swatch",
    defaultValue: "none",
    values: [
      { id: "none", label: "None" },
      { id: "white", label: "White linen", hex: "#f6f4ee", price: 1900 },
      { id: "oxblood", label: "Oxblood silk", hex: "#8a4432", price: 1900 },
      { id: "navy", label: "Navy silk", hex: "#1f2c4c", price: 1900 },
      { id: "gold", label: "Gold paisley", hex: "#c09a48", price: 1900 },
    ],
  },
  {
    id: "suit.service",
    section: "accents",
    label: "Make",
    display: "chip",
    defaultValue: "standard",
    values: [
      { id: "standard", label: "Standard · about 3 weeks" },
      { id: "priority", label: "Priority · about 12 days", price: 6500 },
    ],
  },
];

export const GROUP_BY_ID: Record<string, OptionGroup> = Object.fromEntries(
  OPTION_GROUPS.map((g) => [g.id, g]),
);

export const FABRIC_BY_ID: Record<string, SuitFabric> = Object.fromEntries(
  SUIT_FABRICS.map((f) => [f.id, f]),
);

export function getFabric(id: string | null | undefined): SuitFabric | undefined {
  return id ? FABRIC_BY_ID[id] : undefined;
}

export function getOptionValue(groupId: string, valueId: string) {
  return GROUP_BY_ID[groupId]?.values.find((v) => v.id === valueId);
}

export function defaultOptions(): Record<string, string> {
  return Object.fromEntries(OPTION_GROUPS.map((g) => [g.id, g.defaultValue]));
}

export function defaultConfig(): SuitConfig {
  return {
    v: 1,
    fabric: "house-navy-stretch",
    trouserFabric: null,
    waistcoatFabric: null,
    options: defaultOptions(),
    lining: "oxblood",
    thread: "oxblood",
    monogram: null,
    notes: "",
  };
}

export interface SuitPreset {
  id: string;
  name: string;
  blurb: string;
  fabric: string;
  options: Record<string, string>;
  lining?: string;
}

/** "Start with a base style" — every preset is just a starting config. */
export const SUIT_PRESETS: SuitPreset[] = [
  {
    id: "two-piece",
    name: "Classic Two-Piece",
    blurb: "Single-breasted, two buttons, notch lapel. Where most suits should start.",
    fabric: "classic-navy-s110",
    options: {},
  },
  {
    id: "three-piece",
    name: "Three-Piece",
    blurb: "Adds a matching five-button waistcoat. Weddings, and winter.",
    fabric: "fab-charcoal-wool",
    options: { "suit.pieces": "three", "jacket.lapel": "notch" },
  },
  {
    id: "double-breasted",
    name: "Double-Breasted",
    blurb: "Six buttons, two to fasten, peak lapels and side vents.",
    fabric: "classic-navy-pinstripe",
    options: { "jacket.closure": "db6", "jacket.lapel": "peak", "jacket.lapelWidth": "wide" },
  },
  {
    id: "mandarin",
    name: "Mandarin",
    blurb: "Band collar, no lapels, five buttons — modern ceremonial dress.",
    fabric: "house-black",
    options: { "jacket.closure": "mandarin", "jacket.breastPocket": "none" },
  },
  {
    id: "dinner-suit",
    name: "Dinner Suit",
    blurb: "One-button shawl collar with satin facings in midnight blue.",
    fabric: "premium-midnight-s130",
    options: {
      "jacket.closure": "sb1",
      "jacket.lapel": "shawl",
      "jacket.lapelFacing": "satin",
      "jacket.pockets": "jetted",
      "jacket.vents": "none",
      "trousers.waist": "adjusters",
    },
    lining: "black",
  },
  {
    id: "linen",
    name: "Linen Summer Suit",
    blurb: "Half-lined oatmeal linen with patch pockets. Built for the coast.",
    fabric: "fab-oatmeal-linen",
    options: {
      "jacket.pockets": "patch",
      "jacket.breastPocket": "patch",
      "accents.liningStyle": "half",
      "jacket.shoulder": "natural",
    },
  },
  {
    id: "tweed",
    name: "Tweed Three-Piece",
    blurb: "Donegal tweed, hacking pockets, ticket pocket and suede elbow patches.",
    fabric: "seasonal-donegal-tweed",
    options: {
      "suit.pieces": "three",
      "jacket.closure": "sb3",
      "jacket.pocketSlant": "slanted",
      "jacket.ticketPocket": "ticket",
      "accents.elbowPatches": "brown",
      "trousers.hem": "turnups",
    },
  },
];

export function presetConfig(presetId: string): SuitConfig | null {
  const preset = SUIT_PRESETS.find((p) => p.id === presetId);
  if (!preset) return null;
  const base = defaultConfig();
  return {
    ...base,
    fabric: preset.fabric,
    lining: preset.lining ?? base.lining,
    options: { ...base.options, ...(preset.lining ? { "accents.liningColour": "custom" } : {}), ...preset.options },
  };
}

export const DELIVERY_METHODS = [
  {
    id: "collect",
    label: "Collect at the Ridgeways atelier",
    description: "Includes a final try-on and any last adjustments on the spot.",
    fee: 0,
  },
  {
    id: "nairobi",
    label: "Delivery within Nairobi",
    description: "Pressed and delivered to your door or office.",
    fee: 600,
  },
  {
    id: "kenya",
    label: "Courier elsewhere in Kenya",
    description: "Tracked courier to your town, usually 1–2 days after completion.",
    fee: 1200,
  },
] as const;

export type DeliveryMethodId = (typeof DELIVERY_METHODS)[number]["id"];
